### ISSUE TITLE
Does this work with FreeCAD v0.20dev ?

### ISSUE THREAD

**Issue by luzpaz** [30350n/free2ki#1]
v0.20 is about to be released (it's being blocked by a windows platform packaging issue ATM).

**Comment by 30350n** [comment]
Uhhh no clue tbh. I'd think so because there don't seem to be any large python api changes. I guess you could test it to find out ^^

**Comment by luzpaz** [comment]
The release is planned for next week (said windows packaging issue has been solved) So it may be a good idea to test this before v0.20 release.

**Comment by 30350n** [comment]
Just tested it on a weekly build and after fixing some minor pyside2 related issues, it seems to work fine.
Will test again once v0.20 is actually released/whenever I properly finish up the other projects related to this and release everything :)
Thanks for the heads-up!
